### PR TITLE
danish translation and new template (academic)

### PR DESCRIPTION
**Pull request by thj01**
Before submitting your PR please make sure:

* [x] You worked on the develop branch (or any other branch which was forked from develop),
* [x] Your PR is not targeting the master branch,
* [x] You tested your code and it works.

Thank you!

Added danish dictionary
Added danish translation
Added academic template (html output with TOC, mathjax, highlightjs)

### CODE REVIEW

**Comment by brrd** [comment]
Thanks for contributing. 
Normally in order to help other contributors to understand, test and review your code you are expected to submit a separate PR for each feature and to use explicit commit messages (rather than "Add files via upload"). Could you please do this?

**Comment by thj01** [comment]
It is my first participation in a projekt, and i'm not shure what PR means. And i did it in the browser.

Is there anything i have to do now or is it a "next time" thing?

**Comment by brrd** [comment]
Actually it is a matter of form. As is, your changes are difficult to review and merge into the project.

1) Each PR is supposed to deal with a single feature. In your case, you should create 3 different branches : one for the translation, one for the dictionary and another one for the template. And the end it would make 3 different PR which we could review and work with separately.
2) Commit messages are supposed to give a short description of the changes because they become part of the history: https://github.com/brrd/Abricotine/commits/develop. In your case "Add files via upload" says nothing about what changed in those commits.

It maybe sounds like details but it is really important to keep the code clear and understandable.
Maybe this documentation can help you to understand this process: https://guides.github.com/introduction/flow/

Thank you!

**Comment by brrd** [comment]
Dict and lang files added on the develop branch. 
Template should be submitted and discussed in dedicated PR if you still want it to become a part of the core.

**Pull request closed without merging**
