### PR TITLE
separate `inlineMath` and `displayMath` support && monospace font

### PR DESCRIPTION
**Pull request by Menci**
Inline math syntax: $ x $  
Display math syntax: $$ x $$

I think monospace font is better when writing markdown, so I modified it.  
**Don't fully merge** if you don't like monospace font. :-)

### CODE REVIEW

**Comment by brrd** [comment]
Abricotine used to distinguish inline and display math but as I can remember this was very tricky (display math was not rendering correctly in inline preview) and quite useless since [there is no standard for writing math in markdown](https://github.com/cben/mathdown/wiki/math-in-markdown), so I finally decided to remove this feature. 

You can check commit 5dda88e7e6019961accf3df11c251878e3cba989 where this feature was removed. I don't really like the single `$` syntax because I think it can be very confusing in some situations (such as `$10`), so I used `$$` and `$$$` delimiters (but once again there is no standard).

Actually I would be really interested to know why you think display math is important.

Some other thoughts about your PR:

* The monospace font addition is related to #9 and is a different issue. We are not going to change the default font in Abricotine until the theme feature is released.
* You obviously worked on master branch. Please commit on develop branch otherwise development would become a real pain.

**Comment by brrd** [comment]
>  I think monospace font is better when writing markdown, so I modified it.

Actually Abricotine already uses monospace fonts.

**Comment by Menci** [comment]
I noticed the contents are in monospace fonts, but the titles are not.  
I don't want to modify the style for others, just for myself. But I am not very good at `git` and pushed them all to the repository.

And, sorry, I don't know about that you supported the display math feature and then removed it.  
I just want to put my formula in the center.

I am looking forward to the theme feature.

**Comment by Menci** [comment]
Since math formulas are not in the standard markdown, I can hardly find a editor that supports both inline and display math well on Linux. Some editors(such as CuteMarkEd) "support" this but need escaping for some characters.

On OS X I use MacDown, and on GNU/Linux I can't find an editor I want.

I use markdown for Hexo blogging, and centerd display math formulas are so cool!

**Comment by Menci** [comment]
I think you can add a option for users to choose use what syntax (e.g. how many `$` s) the inline / display math.

And what about #51 ? I want to help fix it but I am not good in Node.js and I don't know about CodeMirror.

And thanks for reminding, I will use `develop` branch next time.

**Comment by brrd** [comment]
> I think you can add a option for users to choose use what syntax (e.g. how many $ s) the inline / display math.

Please see #15.

Actually the way you edited cm-extend-autopreview.js is a bit hacky and could be improved in my opinion. I see a lot of useless code duplication and some parts has not been totally updated. For example, autopreview functions still use the class `.autopreview-math` so preview is not updated as expected when playing with the "Auto Preview" menu entries.

Some other missing parts I noticed:

* Export theme has not been updated.
* Default config has not been updated so the preview is not activated by default.

For all theses reasons I won't merge this PR. If you really want this feature to be added to Abricotine and you need some help in development, then please create a dedicated issue.

**Comment by RoyiAvital** [comment]
Both Display Math and Inline Math are highly important.

I, Personally, prefer the `$...$` and `$$...$$` delimiters because this is what is used in LaTeX.

The best option would be letting the user chose which delimiters to use out of predefined selection (Drop Down Menu in Settings).

**Comment by RoyiAvital** [comment]
Any progress on that?
Please give us separated In Line and Display Math.

Thank You.

**Pull request closed without merging**
