### PR TITLE
Add space between brackets in task list

### LINKED ISSUE #122: GFM Task Lists empty checkbox
Currently, when creating a task list, Abricotine creates an empty checkbox as `* []`. While this ends up rendering correctly in Abricotine, and is easier to manually add the `x` if one wants, GitHub does not render `* []` as an empty checkbox. An empty checkbox according to GitHub should include the space between the brackets: `* [ ]`.

* [] No space
* [ ] Space
* [x] Checked

I think the behavior should be changed to add a space when creating a task list item.

---

```markdown
Currently, when creating a task list, Abricotine creates an empty checkbox as `* []`. While this ends up rendering correctly in Abricotine, and is easier to manually add the `x` if one wants, GitHub does not render `* []` as an empty checkbox. An empty checkbox according to GitHub should include the space between the brackets: `* [ ]`.

* [] No space
* [ ] Space
* [x] Checked

I think the behavior should be changed to add a space when creating a task list item.
```

### PR DESCRIPTION
**Pull request by jacobmischka**
Fixes #122

### CODE REVIEW

**Comment by brrd** [comment]
Please don't work on master branch as requested [here](https://github.com/brrd/Abricotine#contributing). I would merge this if you submit a new PR on develop branch. 
Thanks!

**Comment by jacobmischka** [comment]
Ah whoops. It might be a good idea to put that in a CONTRIBUTING.md so GitHub reminds people when they make issues or PRs, my bad.

**Comment by darahak** [comment]
Good idea, I didn't know Github did that.
I made the same mistake on my first PR.

**Comment by brrd** [comment]
Yes, I was planning to do this. Everybody's doing the same mistake.

**Comment by jacobmischka** [comment]
I do development on `develop` on all my personal repos as well, but the trend in most open source projects seems to just be directly into master for some reason. It didn't even cross my mind to check ha.

As a side note, I believe it should be possible for you to edit the PR and change the branch instead of closing it: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request. Though maybe only requestors can do it, I'm not sure.

**Comment by brrd** [comment]
> As a side note, I believe it should be possible for you to edit the PR and change the branch instead of closing it: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request. Though maybe only requestors can do it, I'm not sure.

Waow, I missed this new feature! Great!

**Comment by nloveladyallen** [comment]
@brrd FYI, you can just add ".diff" to the end of the URL for a PR, and then just wget and git apply.

**Comment by brrd** [comment]
@nloveladyallen Yes but in doing so I assume @jacobmischka wouldn't be credited as the author.

**Pull request closed without merging**
